apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
  namespace: jenkins
  labels:
    app: java-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: java-app

  template:
    metadata:
      labels:
        app: java-app

    spec:
      containers:
        - name: java-app
          image: admindockerrizwan/myapp:v3
          imagePullPolicy: Always

          ports:
            - containerPort: 8080

          # resources:
          #   requests:
          #     cpu: "250m"
          #     memory: "256Mi"
          #   limits:
          #     cpu: "500m"
          #     memory: "512Mi"
---

apiVersion: v1
kind: Service
metadata:
  name: java-app-service
  namespace: jenkins

spec:
  type: LoadBalancer

  selector:
    app: java-app

  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
